repos:
- repo: local
  hooks:
  - id: select-identity+check-identity
    name: Git Identity - check-identity
    entry: C:/Users/N3X15/scoop/apps/python/current/python.exe
    args:
    - V:/CVR/just-mahjong/.selid-hooks/check-identity
    language: system
    require_serial: true
